/*
 * Moreu API
 *
 * This is a moreu server.
 *
 * API version: 1.0
 * Contact: saltbo@foxmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type InlineResponse2002 struct {
	Data *ModelUser `json:"data,omitempty"`
	HttputilJSONResponse *HttputilJsonResponse `json:"httputil.JSONResponse,omitempty"`
}
