/*
 * Moreu API
 *
 * This is a moreu server.
 *
 * API version: 1.0.0
 * Contact: saltbo@foxmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type AllOfinlineResponse2001Data struct {
	List  []ModelUserFormats `json:"list,omitempty"`
	Total int32              `json:"total,omitempty"`
}
