/*
 * Moreu API
 *
 * This is a moreu server.
 *
 * API version: 1.0
 * Contact: saltbo@foxmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type BindBodyConfig struct {
	Key string `json:"key,omitempty"`
	Value string `json:"value,omitempty"`
}
