/*
 * Moreu API
 *
 * This is a moreu server.
 *
 * API version: 1.0
 * Contact: saltbo@foxmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type BindBodyUserPatch struct {
	Activated bool `json:"activated,omitempty"`
	Password string `json:"password,omitempty"`
	Token string `json:"token"`
}
