/*
 * Moreu API
 *
 * This is a moreu server.
 *
 * API version: 1.0.0
 * Contact: saltbo@foxmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package client

type BindBodyUserProfile struct {
	Avatar   string `json:"avatar,omitempty"`
	Bio      string `json:"bio,omitempty"`
	Company  string `json:"company,omitempty"`
	Location string `json:"location,omitempty"`
	Nickname string `json:"nickname,omitempty"`
	Url      string `json:"url,omitempty"`
}
