dist: ./build/release
before:
  hooks:
    - go mod download
builds:
  - id: moreu
    main: ./main.go
    ldflags:
      - -s -w
      - -X github.com/saltbo/moreu/cmd.release={{.Version}}
      - -X github.com/saltbo/moreu/cmd.commit={{.Commit}}
      - -X github.com/saltbo/moreu/cmd.repo={{.GitURL}}
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
archives:
  - name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"
    replacements:
      darwin: macos
    format: tar.gz
    format_overrides:  # archive as zip on Windows
      - goos: windows
        format: zip
    files:
      - none*
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
dockers:
  -
    binaries:
      - moreu
    image_templates:
      - "saltbo/{{.ProjectName}}:{{ .Tag }}"
      - "saltbo/{{.ProjectName}}:latest"